<?php

$labels = array();
$labels['btn_name'] = '&nbsp;Otrs';
$labels['otrs_title'] = 'Σύστημα διαχείρισης αιτημάτων';
$labels['otrs_queue'] = 'Κατηγορία';
$labels['otrs_subject'] = 'Θέμα';
$labels['otrs_description'] = 'Περιγραφή';
$labels['otrs_priority'] = 'Προτεραιότητα';
$labels['otrs_priority_1'] = 'πολύ χαμηλή';
$labels['otrs_priority_2'] = 'χαμηλή';
$labels['otrs_priority_3'] = 'κανονική';
$labels['otrs_priority_4'] = 'υψηλή';
$labels['otrs_priority_5'] = 'πολύ υψηλή';
$labels['otrs_submit'] = 'Υποβολή';
$labels['otrs_ticket_saved'] = 'Το αίτημά σας καταγράφηκε';
$labels['otrs_ticket_details'] = 'Τα στοιχεία του αιτήματος είναι';
$labels['otrs_ticket_number'] = 'Αριθμός αιτήματος';
$labels['otrs_ticket_id'] = 'Αναγνωριστικό αιτήματος';
$labels['otrs_article_id'] = 'Αναγνωριστικό άρθρου';
$labels['otrs_back'] = 'Επιστροφή';
//$labels['otrs_'] = '';
//$labels['otrs_'] = '';
//$labels['otrs_'] = '';

?>
