<?php

$labels = array();
$labels['btn_name'] = '&nbsp;Otrs';
$labels['otrs_title'] = 'Ticketing System';
$labels['otrs_queue'] = 'Queue';
$labels['otrs_subject'] = 'Subject';
$labels['otrs_description'] = 'Description';
$labels['otrs_priority'] = 'Priority';
$labels['otrs_priority_1'] = 'very low';
$labels['otrs_priority_2'] = 'low';
$labels['otrs_priority_3'] = 'normal';
$labels['otrs_priority_4'] = 'high';
$labels['otrs_priority_5'] = 'very high';
$labels['otrs_submit'] = 'Submit';
$labels['otrs_ticket_saved'] = 'Your ticket has been saved';
$labels['otrs_ticket_details'] = 'Ticket details';
$labels['otrs_ticket_number'] = 'Ticket number';
$labels['otrs_ticket_id'] = 'Ticket ID';
$labels['otrs_article_id'] = 'Article ID';
$labels['otrs_back'] = 'Back';

?>
